project:
  type: website
  output-dir: docs
execute: 
  freeze: auto
website:
  announcement:
    icon: info-circle
    dismissable: false
    type: primary
    position: above-navbar
    content: "Website updated; 01.02.2026"
  title: "EDS241/ESM244"
  favicon: images/bren-hex.png
  navbar:
    right:
      - href: index.qmd
        text: home
      - text: syllabus
        href: https://docs.google.com/document/d/1YDvge99F26UFSNJ_LA1-2ZsbfRj_U4AJoYtVxD1dvV8/edit?usp=sharing
        target: _blank
      - text: course materials
        menu:
          - text: week 1 (1/06/26)
            href: course-materials/week1.qmd
          - text: week 2 (1/13/26)
            href: course-materials/week2.qmd
          - text: week 3 (1/20/26)
            href: course-materials/week3.qmd
          - text: week 4 (1/27/25)
            href: course-materials/week4.qmd          
          - text: week 5 (2/03/25)
            href: course-materials/week5.qmd
          - text: week 6 (2/10/25)
            href: course-materials/week6.qmd        
          #- text: week 7 (17/02/25)
          #  href: course-materials/week7.qmd
          #- text: week 8 (24/02/25)
          #  href: course-materials/week8.qmd    
          #- text: week 9 (03/03/25)
          #  href: course-materials/week9.qmd  
          #- text: week 10 (10/03/25)
          #  href: course-materials/week10.qmd  
      #- text: assignments
      #  href: course-materials/assignments.qmd
      #- text: resources
      #  href: course-materials/resources.qmd
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/UCSB-MEDS/EDS-website-template
          - text: Report a Bug
            url: https://github.com/UCSB-MEDS/EDS-website-template/issues
  page-footer:
    background: dark
    right: This website is built with [{{< fa brands github title="the github octocat logo" >}}](https://github.com/UCSB-MEDS/EDS-website-template) and [Quarto](https://quarto.org/)
    left: This work is licensed under the <a href="https://opensource.org/licenses/MIT" target="_blank">MIT License</a> Â© 2024

format:
  html:
    theme: meds-website-styles.scss
    page-layout: full
    toc: true
    title-block-banner: true



